# Topic 1 – What is Data Preprocessing?

Data preprocessing is the process of converting raw data into clean and machine-learning-ready data.

### Simple Example

Raw data may contain missing, duplicate, invalid, or inconsistent values.

Example:

Age = 25, NaN, 150

After preprocessing:

Age = 25, 30, 30

### Real-World Example

Hospital data may contain missing patient age or incorrect values. Preprocessing cleans the data.

### Business Example

Customer data may contain missing salary, duplicate customers, or inconsistent gender values. Preprocessing fixes these problems.

### AI/ML Use Case

Before training a machine-learning model, raw data must be cleaned and converted into a suitable format.

### Why Required?

Preprocessing improves data quality and helps the ML model learn correctly.

### Problem Solved

It handles missing, incorrect, duplicate, and inconsistent data.

---

In [1]:

## Step 3 – Implement the Concept

### Python

import pandas as pd

data = {
    "Age": [25, None, 30],
    "Gender": ["Male", "male", "Female"]
}

df = pd.DataFrame(data)

print("Before:")
print(df)

# Fill missing Age
df["Age"] = df["Age"].fillna(df["Age"].median())

# Standardize Gender
df["Gender"] = df["Gender"].str.capitalize()

print("After:")
print(df)


Before:
    Age  Gender
0  25.0    Male
1   NaN    male
2  30.0  Female
After:
    Age  Gender
0  25.0    Male
1  27.5    Male
2  30.0  Female


### New Python Methods Used

**fillna()** → Fills missing values.

**median()** → Finds the middle value of numerical data.

**str.capitalize()** → Converts the first character to uppercase and the remaining characters to lowercase.

Example:

"male" → "Male"

"FEMALE" → "Female"

### Explanation

- Before preprocessing → Age has a missing value and Gender is inconsistent.
- `fillna()` → Fills the missing Age.
- `median()` → Finds the value used to fill the missing Age.
- `str.capitalize()` → Makes Gender values consistent.
- After preprocessing → The data is cleaner and ready for further ML preprocessing.
- Clean data helps the ML model learn better.

# Topic 2 – Why is Data Preprocessing Required?

Data preprocessing is required because raw data often contains problems such as missing values, duplicates, incorrect values, and inconsistent formats.

### Simple Example

Raw data:

Age = 25, NaN, 30

The missing value can cause problems during ML training.

After preprocessing:

Age = 25, 27, 30

### Real-World Example

Hospital data may contain missing patient details or incorrect values. Preprocessing makes the data reliable.

### Business Example

Customer data may contain duplicate customers or missing salary information. Cleaning the data prevents incorrect business decisions.

### AI/ML Use Case

An ML model cannot properly learn from poor-quality data. Preprocessing prepares the data before model training.

### Why Required?

It helps to:

- Handle missing values
- Remove duplicates
- Fix incorrect values
- Make data consistent
- Prepare data for ML

### Problem Solved

It improves data quality and helps the model produce more reliable predictions.


In [3]:

## Step 3 – Implement the Concept

### Python

import pandas as pd

data = {
    "Age": [25, None, 30, 30],
    "Gender": ["Male", "Male", "male", "Female"]
}

df = pd.DataFrame(data)

print("Before:")
print(df)

# Remove duplicate rows
df = df.drop_duplicates()

# Fill missing Age
df["Age"] = df["Age"].fillna(df["Age"].median())

# Standardize Gender
df["Gender"] = df["Gender"].str.capitalize()

print("\nAfter:")
print(df)


Before:
    Age  Gender
0  25.0    Male
1   NaN    Male
2  30.0    male
3  30.0  Female

After:
    Age  Gender
0  25.0    Male
1  30.0    Male
2  30.0    Male
3  30.0  Female



### New Python Methods Used

**drop_duplicates()** → Removes duplicate rows.

Example:

[30, "male"] repeated twice → keeps only one row.

**fillna()** → Fills missing values.

**median()** → Finds the middle value of numerical data.

**str.capitalize()** → Converts the first letter to uppercase and the remaining letters to lowercase.

Example:

"male" → "Male"

### Explanation

- Before preprocessing → Data contains missing, duplicate, and inconsistent values.
- `drop_duplicates()` → Removes duplicate records.
- `fillna()` → Handles the missing Age.
- `str.capitalize()` → Makes Gender values consistent.
- After preprocessing → Data is cleaner and more suitable for ML.
- Clean data helps the model learn better patterns

# Topic 3 – Raw Data vs Clean Data

## Step 2 – Demonstrate the Concept

### Simple Example

Raw data may contain:

- Missing values
- Duplicate rows
- Incorrect values
- Inconsistent formats

Example:

| Age | Gender |
|---:|---|
| 25 | Male |
| NaN | male |
| 150 | Female |
| 25 | Male |

Clean data:

| Age | Gender |
|---:|---|
| 25 | Male |
| 30 | Male |
| 30 | Female |

### Real-World Example

Hospital data collected from different sources may contain missing, duplicate, or incorrect patient information.

### Business Example

An e-commerce company may have duplicate customer records and inconsistent customer details.

### AI/ML Use Case

ML models should receive clean data so they can learn meaningful patterns.

### Why Required?

Raw data can produce incorrect analysis and poor ML predictions.

### Problem Solved

Preprocessing converts raw, messy data into clean and usable data.

---


### Explanation

Before preprocessing:
- Data contains a missing Age.
- Gender values are inconsistent.
- Duplicate rows may exist.

After preprocessing:
- Missing Age is filled.
- Gender is standardized.
- Duplicate rows are removed.

Clean data is more suitable for Machine Learning.

In [6]:

## Step 3 – Implement the Concept

### Python

import pandas as pd

data = {
    "Age": [25, None, 30, 30],
    "Gender": ["Male", "male", "Female", "Female"]
}

df = pd.DataFrame(data)

print("Raw Data:")
print(df)

# Standardize Gender
df["Gender"] = df["Gender"].str.capitalize()

# Remove duplicates
df = df.drop_duplicates()

# Fill missing Age
df["Age"] = df["Age"].fillna(df["Age"].median())

print("\nClean Data:")
print(df)


Raw Data:
    Age  Gender
0  25.0    Male
1   NaN    male
2  30.0  Female
3  30.0  Female

Clean Data:
    Age  Gender
0  25.0    Male
1  27.5    Male
2  30.0  Female



### New Python Methods

**pd.DataFrame()** → Creates a table from the data.

**str.capitalize()** → Converts the first letter to uppercase.

Example: "male" → "Male"

**drop_duplicates()** → Removes duplicate rows.

**fillna()** → Fills missing values.

**median()** → Finds the middle value of numerical data.

# Topic 4 – Data Quality

### Simple Example

Good-quality data should be:

- Correct
- Complete
- Consistent
- Valid
- Reliable

Example:

Age = 25 → Good quality

Age = 250 → Poor quality

### Real-World Example

Hospital data with incorrect patient age or missing blood pressure has poor data quality.

### Business Example

Customer data with wrong phone numbers or duplicate customers can lead to incorrect business decisions.

### AI/ML Use Case

An ML model trained on poor-quality data may learn incorrect patterns and give poor predictions.

### Why Required?

Good data quality helps us perform accurate analysis and build reliable ML models.

### Problem Solved

Data quality checks help identify and fix errors before using the data.

---


In [7]:

### Python

import pandas as pd

data = {
    "Age": [25, 30, 150, 40],
    "Salary": [30000, 40000, 50000, None]
}

df = pd.DataFrame(data)

print("Data:")
print(df)

# Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Check invalid age
print("\nInvalid Age:")
print(df[df["Age"] > 120])

Data:
   Age   Salary
0   25  30000.0
1   30  40000.0
2  150  50000.0
3   40      NaN

Missing Values:
Age       0
Salary    1
dtype: int64

Invalid Age:
   Age   Salary
2  150  50000.0



## Step 3 – Implement the Concept


### New Python Methods

**isnull()** → Checks whether a value is missing.

Example:

NaN → True

25 → False

**sum()** → Counts the missing values.

**df[condition]** → Filters rows based on a condition.

Example:

df["Age"] > 120 → Finds ages greater than 120.

### Explanation

Before preprocessing:
- Salary contains a missing value.
- Age contains an invalid value.

After identifying these problems, we can handle them using suitable preprocessing techniques.

Good data quality helps Machine Learning models learn from reliable data.

# Topic 5 – Data Consistency

## Step 2 – Demonstrate the Concept

### Simple Example

Data consistency means the same information should be stored in the same format.

Example:

Male, male, M, MALE

These represent the same category but are inconsistent.

After preprocessing:

Male, Male, Male, Male

### School Example

Student gender may be recorded as:

Male, male, M

We can standardize all values to:

Male

### Real-World Example

Hospital data may contain:

Chennai, chennai, CHENNAI

These should be standardized to one format.

### Business Example

Customer location may be recorded as:

Chennai, Chennai City, chennai

Inconsistent values can affect reports and analysis.

### AI/ML Use Case

An ML model may treat "Male", "male", and "M" as different categories if they are not standardized.

### Why Required?

Consistency ensures that the same information is represented in the same format.

### Problem Solved

It prevents incorrect categories and improves data quality.

---

In [8]:

## Step 3 – Implement the Concept

### Python

import pandas as pd

data = {
    "Student": ["Arun", "Kumar", "Priya", "Ravi"],
    "Gender": ["Male", "male", "FEMALE", "Female"]
}

df = pd.DataFrame(data)

print("Before:")
print(df)

# Standardize Gender
df["Gender"] = df["Gender"].str.capitalize()

print("\nAfter:")
print(df)


Before:
  Student  Gender
0    Arun    Male
1   Kumar    male
2   Priya  FEMALE
3    Ravi  Female

After:
  Student  Gender
0    Arun    Male
1   Kumar    Male
2   Priya  Female
3    Ravi  Female



### New Python Method

**str.capitalize()** → Converts the first character to uppercase and the remaining characters to lowercase.

Example:

"male" → "Male"

"FEMALE" → "Female"

### Explanation

Before preprocessing:

Male, male, FEMALE, Female

After preprocessing:

Male, Male, Female, Female

The data is now consistent and easier to use for analysis and Machine Learning.

# Topic 6 – Data Completeness

## Step 2 – Demonstrate the Concept

### Simple Example

Data completeness means required information should not be missing.

Example:

| Student | Age | Marks |
|---|---:|---:|
| Arun | 15 | 85 |
| Kumar | NaN | 90 |
| Priya | 16 | NaN |

Age and Marks are missing.

### School Example

A school database may have students with missing:

- Age
- Marks
- Class
- Attendance

Missing information makes analysis difficult.

### Real-World Example

Hospital records may have missing patient age or medical information.

### Business Example

Customer records may have missing phone numbers or purchase information.

### AI/ML Use Case

ML models need complete input features to learn properly. Missing values must be handled before training.

### Why Required?

Complete data provides more information for analysis and ML.

### Problem Solved

It identifies and handles missing information.

---

In [9]:

## Step 3 – Implement the Concept

### Python

import pandas as pd

data = {
    "Student": ["Arun", "Kumar", "Priya"],
    "Age": [15, None, 16],
    "Marks": [85, 90, None]
}

df = pd.DataFrame(data)

print("Before:")
print(df)

# Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Fill missing values
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Marks"] = df["Marks"].fillna(df["Marks"].median())

print("\nAfter:")
print(df)


Before:
  Student   Age  Marks
0    Arun  15.0   85.0
1   Kumar   NaN   90.0
2   Priya  16.0    NaN

Missing Values:
Student    0
Age        1
Marks      1
dtype: int64

After:
  Student   Age  Marks
0    Arun  15.0   85.0
1   Kumar  15.5   90.0
2   Priya  16.0   87.5



### New Python Methods

**isnull()** → Finds missing values.

**sum()** → Counts the missing values.

**fillna()** → Fills missing values.

**median()** → Finds the middle value of a numerical column.

### Explanation

Before preprocessing:

- Age is missing for Kumar.
- Marks are missing for Priya.

After preprocessing:

- Missing Age is filled.
- Missing Marks are filled.

The dataset is now more complete and suitable for Machine Learning.

# Topic 7 – Data Accuracy

## Step 2 – Demonstrate the Concept

### Simple Example

Data accuracy means the data should correctly represent the real-world value.

Example:

Actual Age = 15

Recorded Age = 51

The recorded data is inaccurate.

### School Example

A student's actual mark is 85, but the database shows 58.

The data is inaccurate and should be corrected.

### Real-World Example

A hospital records a patient's blood pressure as 250 instead of the actual value 120.

This is inaccurate data.

### Business Example

A customer actually purchased ₹5,000 worth of products, but the system records ₹500.

This can affect sales reports.

### AI/ML Use Case

If inaccurate data is used for training, the ML model may learn incorrect patterns and produce unreliable predictions.

### Why Required?

Accurate data helps us make correct decisions and build reliable ML models.

### Problem Solved

It identifies and corrects values that do not represent the actual information.

In [11]:

## Step 3 – Implement the Concept

### Python

import pandas as pd

data = {
    "Student": ["Arun", "Kumar", "Priya"],
    "Marks": [85, 150, 90]
}

df = pd.DataFrame(data)

print("Before:")
print(df)

# Find inaccurate/invalid marks
invalid_marks = df[df["Marks"] > 100]

print("\nInvalid Marks:")
print(invalid_marks)

# Replace invalid marks with missing value
df.loc[df["Marks"] > 100, "Marks"] = None

print("\nAfter:")
print(df)


Before:
  Student  Marks
0    Arun     85
1   Kumar    150
2   Priya     90

Invalid Marks:
  Student  Marks
1   Kumar    150

After:
  Student  Marks
0    Arun   85.0
1   Kumar    NaN
2   Priya   90.0



### New Python Methods

**df[condition]** → Filters rows that satisfy a condition.

**loc[]** → Selects specific rows or columns for modification.

Example:

df.loc[df["Marks"] > 100, "Marks"] = None

This finds marks greater than 100 and replaces them with a missing value.

### Explanation

Before preprocessing:

Kumar's mark is 150, which is not a valid school mark.

After preprocessing:

150 is identified and replaced with a missing value.

The incorrect value can then be handled using an appropriate missing-value technique.

Accurate data helps Machine Learning models learn correct patterns.

# Topic 8 – Data Validity

## Step 2 – Demonstrate the Concept

Data validity means data must follow predefined rules.

### Simple Example

Marks should be between 0 and 100.

85 → Valid  
150 → Invalid

### School Example

Age = 15 → Valid  
Age = 150 → Invalid  
Marks = 90 → Valid  
Marks = -10 → Invalid

### Real-World Example

A patient's age cannot normally be negative.

### Business Example

A product price should not be negative.

### AI/ML Use Case

Invalid values can confuse an ML model and lead to incorrect predictions.

### Why Required?

Validity checks ensure that data follows the rules defined for the dataset.

### Problem Solved

It identifies values outside the allowed range.


In [12]:

## Step 3 – Implement the Concept

import pandas as pd

data = {
    "Student": ["Arun", "Kumar", "Priya", "Ravi"],
    "Marks": [85, 150, 90, -10]
}

df = pd.DataFrame(data)

print("Before:")
print(df)

invalid_marks = df[(df["Marks"] < 0) | (df["Marks"] > 100)]

print("\nInvalid Marks:")
print(invalid_marks)


Before:
  Student  Marks
0    Arun     85
1   Kumar    150
2   Priya     90
3    Ravi    -10

Invalid Marks:
  Student  Marks
1   Kumar    150
3    Ravi    -10



### New Python Concepts

**df[condition]** → Filters rows based on a condition.

**<** → Checks whether a value is less than another value.

**>** → Checks whether a value is greater than another value.

**|** → Means OR. It checks whether either condition is True.

### Explanation

The valid mark range is 0 to 100.

Before preprocessing:
150 and -10 are invalid.

The code identifies these invalid values.

After preprocessing, these values can be corrected, replaced, or removed.

Validity checking helps ensure that only meaningful data is used for Machine Learning.

# Topic 9 – Data Integrity

## Step 2 – Demonstrate the Concept

Data integrity means data should remain correct, reliable, and properly connected.

### Simple Example

A student's marks should belong to the correct student.

Arun → 85 marks  
Kumar → 90 marks

The marks should not be assigned to the wrong student.

### School Example

A school database may have:

Student_ID = 101  
Student_Name = Arun  
Marks = 85

The student ID, name, and marks should belong to the same student.

### Real-World Example

In a hospital, a patient's medical report should be connected to the correct patient.

### Business Example

An order should be linked to the correct customer.

Customer_ID = 101 → Order_ID = 5001

### AI/ML Use Case

Incorrect relationships between data can cause an ML model to learn wrong patterns.

### Why Required?

Data integrity ensures that data and relationships between records remain correct.

### Problem Solved

It prevents incorrect, corrupted, or mismatched data.


In [14]:

## Step 3 – Implement the Concept

import pandas as pd

data = {
    "Student_ID": [101, 102, 103],
    "Student_Name": ["Arun", "Kumar", "Priya"],
    "Marks": [85, 90, 95]
}

df = pd.DataFrame(data)

print("Student Data:")
print(df)

# Check duplicate Student IDs
print("\nDuplicate Student IDs:")
print(df[df["Student_ID"].duplicated()])


Student Data:
   Student_ID Student_Name  Marks
0         101         Arun     85
1         102        Kumar     90
2         103        Priya     95

Duplicate Student IDs:
Empty DataFrame
Columns: [Student_ID, Student_Name, Marks]
Index: []



### New Python Method

**duplicated()** → Checks whether a value has appeared before.

Example:

101, 102, 101

The second 101 is identified as a duplicate.

### Explanation

Before checking integrity, we need to ensure that each Student_ID uniquely identifies a student.

If duplicate IDs exist, student records may become mixed or incorrect.

Good data integrity ensures that the correct information belongs to the correct record.

This helps Machine Learning models learn from correctly related data.

# Topic 10 – Data Leakage

## Step 2 – Demonstrate the Concept

Data leakage occurs when information from outside the training data is used while training an ML model.

### Simple Example

Suppose we want to predict a student's final exam result.

If we use the student's final exam marks as an input feature, the model already knows the answer.

This is data leakage.

### School Example

We want to predict:

Pass or Fail

Features:

- Attendance
- Internal Marks
- Study Hours

If we also give the model the Final Exam Result, leakage occurs.

### Real-World Example

A hospital model predicts whether a patient will be discharged.

If the model uses information that is only available after discharge, leakage occurs.

### Business Example

A company predicts whether a customer will leave.

If we use a field that is updated only after the customer leaves, the model gets future information.

### AI/ML Use Case

Data leakage can produce very high accuracy during testing but poor performance on real-world data.

### Why Required?

Preventing leakage ensures that the model learns only from information that would actually be available when making predictions.

### Problem Solved

It prevents unrealistic model performance and improves real-world reliability.


In [15]:

## Step 3 – Implement the Concept

import pandas as pd
from sklearn.model_selection import train_test_split

data = {
    "Study_Hours": [2, 4, 5, 1, 6, 3],
    "Attendance": [60, 80, 90, 50, 95, 70],
    "Final_Marks": [40, 65, 80, 30, 90, 55]
}

df = pd.DataFrame(data)

# Separate features and target
X = df[["Study_Hours", "Attendance"]]
y = df["Final_Marks"]

# Split the data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training Data:")
print(X_train)

print("\nTest Data:")
print(X_test)


Training Data:
   Study_Hours  Attendance
5            3          70
2            5          90
4            6          95
3            1          50

Test Data:
   Study_Hours  Attendance
0            2          60
1            4          80


# Topic 11 – Training Data

## Step 2 – Demonstrate the Concept

Training data is the part of the dataset used to teach the ML model.

### Simple Example

Suppose we have 100 student records.

70 records → Training data

The model learns patterns from these 70 records.

### School Example

To predict student performance, the model learns from:

- Study Hours
- Attendance
- Previous Marks

These values are provided in the training data.

### Real-World Example

A hospital model can learn from previous patient records to predict future patient outcomes.

### Business Example

A company can use previous customer data to train a model to predict customer purchases.

### AI/ML Use Case

Training data is used by the ML algorithm to learn relationships between input features and the target.

### Why Required?

The model needs examples to learn patterns.

### Problem Solved

Training data allows the ML model to learn from historical data and make predictions on new data.


In [16]:

## Step 3 – Implement the Concept

import pandas as pd
from sklearn.model_selection import train_test_split

data = {
    "Study_Hours": [2, 4, 5, 1, 6, 3],
    "Attendance": [60, 80, 90, 50, 95, 70],
    "Marks": [40, 65, 80, 30, 90, 55]
}

df = pd.DataFrame(data)

X = df[["Study_Hours", "Attendance"]]
y = df["Marks"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training Features:")
print(X_train)

print("\nTraining Target:")
print(y_train)


Training Features:
   Study_Hours  Attendance
5            3          70
2            5          90
4            6          95
3            1          50

Training Target:
5    55
2    80
4    90
3    30
Name: Marks, dtype: int64



### New Python Concepts

**train_test_split()** → Splits the dataset into training and testing data.

**X** → Input features.

**y** → Target value.

**test_size=0.2** → Uses 20% for testing and 80% for training.

**random_state=42** → Keeps the same split every time.

### Explanation

Before splitting:

All student records are together.

After splitting:

80% → Training data

20% → Test data

The model learns patterns from the training data.

Training data is important because it provides examples from which the ML model learns.

# Topic 12 – Validation Data

## Step 2 – Demonstrate the Concept

Validation data is used to check and improve the ML model during development.

### Simple Example

Suppose we have 100 student records:

70 → Training  
15 → Validation  
15 → Test

### School Example

We train a model using student study hours and attendance.

Validation data helps us check which model or settings work better before final testing.

### Real-World Example

A hospital can use validation data to compare different models for predicting patient outcomes.

### Business Example

An e-commerce company can use validation data to choose the best model for predicting customer purchases.

### AI/ML Use Case

Validation data is mainly used for:

- Model selection
- Hyperparameter tuning
- Comparing model performance

### Why Required?

It helps improve the model without using the final test data.

### Problem Solved

It prevents us from repeatedly using the test data while developing the model.


In [17]:

## Step 3 – Implement the Concept

import pandas as pd
from sklearn.model_selection import train_test_split

data = {
    "Study_Hours": [2, 4, 5, 1, 6, 3, 7, 8, 2, 5],
    "Attendance": [60, 80, 90, 50, 95, 70, 98, 100, 65, 85],
    "Marks": [40, 65, 80, 30, 90, 55, 95, 98, 45, 75]
}

df = pd.DataFrame(data)

X = df[["Study_Hours", "Attendance"]]
y = df["Marks"]

# First split: Training and Temporary data
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.30, random_state=42
)

# Second split: Validation and Test
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.50, random_state=42
)

print("Training Data:")
print(X_train)

print("\nValidation Data:")
print(X_val)

print("\nTest Data:")
print(X_test)


Training Data:
   Study_Hours  Attendance
0            2          60
7            8         100
2            5          90
9            5          85
4            6          95
3            1          50
6            7          98

Validation Data:
   Study_Hours  Attendance
5            3          70

Test Data:
   Study_Hours  Attendance
8            2          65
1            4          80



### New Python Concept

**X_temp** → Temporary data created after the first split.

It is later divided into validation and test data.

### Explanation

First split:

70% → Training  
30% → Temporary

Second split:

15% → Validation  
15% → Test

Training data is used to train the model.

Validation data is used to improve or select the model.

Test data is kept for final evaluation.

# Topic 13 – Test Data

## Step 2 – Demonstrate the Concept

Test data is the data used to evaluate the final performance of an ML model.

### Simple Example

Suppose we have 100 student records:

70 → Training  
15 → Validation  
15 → Test

The test data is kept separate and unseen during training.

### School Example

We train a model using student Study Hours and Attendance.

After training, test data is used to check how well the model predicts marks for students it has not seen before.

### Real-World Example

A hospital can use unseen patient records to check how accurately a trained model predicts patient outcomes.

### Business Example

An e-commerce company can use unseen customer records to measure how accurately the model predicts purchases.

### AI/ML Use Case

Test data is used for final evaluation using metrics such as:

- Accuracy
- Precision
- Recall
- F1-score
- Mean Squared Error

### Why Required?

Test data shows how well the model performs on unseen data.

### Problem Solved

It helps measure whether the trained model can generalize to new data.


In [18]:

## Step 3 – Implement the Concept

import pandas as pd
from sklearn.model_selection import train_test_split

data = {
    "Study_Hours": [2, 4, 5, 1, 6, 3, 7, 8, 2, 5],
    "Attendance": [60, 80, 90, 50, 95, 70, 98, 100, 65, 85],
    "Marks": [40, 65, 80, 30, 90, 55, 95, 98, 45, 75]
}

df = pd.DataFrame(data)

X = df[["Study_Hours", "Attendance"]]
y = df["Marks"]

# Split training and test data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42
)

print("Training Data:")
print(X_train)

print("\nTest Data:")
print(X_test)

Training Data:
   Study_Hours  Attendance
5            3          70
0            2          60
7            8         100
2            5          90
9            5          85
4            6          95
3            1          50
6            7          98

Test Data:
   Study_Hours  Attendance
8            2          65
1            4          80


### New Python Concept

**test_size=0.20** → Keeps 20% of the data for testing.

### Explanation

Before splitting:

All student records are together.

After splitting:

80% → Training data

20% → Test data

The model learns from the training data.

The test data is kept unseen and used only for final evaluation.

This helps us understand how well the ML model performs on new data.

# Topic 14 – Preprocessing Pipeline

## Step 2 – Demonstrate the Concept

A preprocessing pipeline is a sequence of preprocessing steps applied to data before Machine Learning.

### Simple Example

Raw Data
→ Missing Values
→ Encoding
→ Scaling
→ ML Model

### School Example

Student data may contain:

Age, Gender, Study Hours, Marks

Pipeline:

Missing values
→ Fix categories
→ Convert categorical data
→ Scale numerical data
→ Train ML model

### Real-World Example

Hospital data can go through:

Missing value handling
→ Encoding
→ Scaling
→ ML model

### Business Example

Customer data can go through:

Clean data
→ Encode categories
→ Scale features
→ Predict customer purchases

### AI/ML Use Case

A pipeline ensures the same preprocessing steps are applied consistently to training and new data.

### Why Required?

It makes preprocessing organized, repeatable, and helps prevent data leakage.

### Problem Solved

It avoids manually performing different preprocessing steps every time.


In [19]:

## Step 3 – Implement the Concept

import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

data = {
    "Study_Hours": [2, 4, None, 6, 5],
    "Attendance": [60, 80, 90, None, 85]
}

df = pd.DataFrame(data)

print("Before:")
print(df)

pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

processed_data = pipeline.fit_transform(df)

print("\nAfter:")
print(processed_data)


Before:
   Study_Hours  Attendance
0          2.0        60.0
1          4.0        80.0
2          NaN        90.0
3          6.0         NaN
4          5.0        85.0

After:
[[-1.73369023 -1.89400743]
 [-0.22613351  0.04856429]
 [ 0.15075567  1.01985016]
 [ 1.28142321  0.29138576]
 [ 0.52764485  0.53420722]]



### New Python Concepts

**Pipeline()** → Combines multiple preprocessing steps into one sequence.

**SimpleImputer()** → Handles missing values.

**StandardScaler()** → Scales numerical values so they are on a similar scale.

**fit_transform()** → Learns the preprocessing rules and applies them to the data.

### Explanation

Before preprocessing:

- Study Hours has a missing value.
- Attendance has a missing value.
- Features are on their original scales.

Pipeline performs:

Missing values
→ Median imputation
→ Scaling

After preprocessing:

- Missing values are handled.
- Numerical features are scaled.
- Data is ready for Machine Learning.

A pipeline makes preprocessing consistent and reduces the chance of data leakage.